
name: CI Pipeline

# Définit quand le workflow doit s'exécuter
on:
  push:
    branches: [ main, dev, node_server ]
  pull_request:
    branches: [ main, dev, node_server ]

# Jobs à exécuter
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code source
    - uses: actions/checkout@v2

    # Étape de construction du projet (ajustez selon votre projet)
    - name: Build Project
      run: |
        echo "Ajoutez ici les commandes pour construire votre projet"
        npm ci
        npm run build --if-present
        npm run test --if-present

    # Construction de l'image Docker
    - name: Build Docker Image
      run: docker build -t projet_pevops:${{ github.sha }} .

    # Connexion au Docker Hub (ou autre registre)
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.ACCESS_TOKEN_DOCKERHUB }}

    # Push de l'image Docker
    - name: Push Docker Image
      run: docker push projet-devops:${{ github.sha }}
